name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install toolchain
        run: sudo apt-get update && sudo apt-get install cmake ninja-build gcc g++

      - name: Run tests
        run: ./unit_test.sh
