name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy
          override: true      
      - name: Run tests
        run: ./unit_test.sh
